trigger: none

jobs:
  - job: BuildCollaterals
    pool:
      vmImage: 'vs2017-win2016'
    steps:

    - task: AzureCLI@1
      displayName: 'Download CST'
      inputs:
        azureSubscription: 'Silicon team: Cosine IOT Services Azure Internal Consumption'
        scriptLocation: inlineScript
        inlineScript: |
          az storage blob download --account-name siliconfirmware --container-name cst --name cst.tar.gz --file $(Build.SourcesDirectory)\cst.tar.gz

    - task: CopyFiles@2
      inputs:
        contents: '$(Build.SourcesDirectory)\cst.tar.gz'
        targetFolder: $(Build.ArtifactStagingDirectory)\cst
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)\cst
        artifactName: Cst

    - task: AzureCLI@1
      displayName: 'Fetch ARM Windows IoT Core Packages 1809 LTSC from Azure Storage'
      inputs:
        azureSubscription: 'Silicon team: Cosine IOT Services Azure Internal Consumption'
        scriptLocation: inlineScript
        inlineScript: |
          az storage blob download --account-name imxiotcorestorage --container-name imxbuildinputs --name Windows_10_IoT_Core_ARM_Packages.msi --file $(Build.SourcesDirectory)\Windows_10_IoT_Core_ARM_Packages.msi

    - task: AzureCLI@1
      displayName: 'Fetch ARM64 Windows IoT Core Packages 1809 LTSC from Azure Storage'
      inputs:
        azureSubscription: 'Silicon team: Cosine IOT Services Azure Internal Consumption'
        scriptLocation: inlineScript
        inlineScript: |
          az storage blob download --account-name imxiotcorestorage --container-name imxbuildinputs --name Windows_10_IoT_Core_ARM64_Packages.msi --file $(Build.SourcesDirectory)\Windows_10_IoT_Core_ARM64_Packages.msi

    - task: CopyFiles@2
      inputs:
        contents: '$(Build.SourcesDirectory)\*.msi'
        targetFolder: $(Build.ArtifactStagingDirectory)\msi
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)\msi
        artifactName: BuildCollaterals